# Generated by Django 4.2.17 on 2024-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('release_date', models.DateField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
