# Generated by Django 4.2.17 on 2024-12-10 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='customer',
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default='films/default.jpg', upload_to='films/'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
